### ISSUE TITLE
[feature] Sidebar icons

### ISSUE THREAD

**Issue by dxps** [nsubiron/sublime-theme-solarized-space#1]
Hi nsubiron,

I really love this theme! It is one of my favourites.
One additional feature I would like to have with this theme is the sidebar icons.
Is that possible? Can I somehow help you with it?

Thank you.

**Comment by nsubiron** [comment]
Hi visvadw,

Glad you ask, actually I worked on this theme some time ago and added sidebar icons, but I was pretty busy to test it properly so I haven't pushed it yet. I'll take a look again and push what I have.

Thanks for the feedback!

**Comment by nsubiron** [comment]
Added in release v0.4.0

**Comment by dxps** [comment]
Hi nsubiron,

Thank you very much for the update!

I've noticed that the new release comes with some extra padding:
![image](https://cloud.githubusercontent.com/assets/14140226/15096462/4018bbe8-1501-11e6-8803-88fd724a5ef7.png)

Am I correct?

Besides this, there is an option to change the folder icons?

Once again, thank you very much for the feedback and effort you put into this!

**Comment by nsubiron** [comment]
Hi visvadw,

Yes, I also noticed the extra padding, it's not intentional. I just opened an issue for that (#4).

And no, by now I only added one icon for folders, there is no option for changing it. Can be overridden though if you really want to by creating the folder `Packages/Theme - Solarized Space/images` and adding there the icons `folder-icon.png` and `folder_open-icon.png`.

**Comment by dxps** [comment]
Hi nsubiron,

Changing the files is a quick and easy option, so that's nice.
However, I could not find the aforementioned location on my (OSX) system.
Neither in
   `/Users/<user>/Library/Application Support/Sublime Text 3/Packages`
nor in
   `/Users/<user>/Library/Application Support/Sublime Text 3/Installed Packages`

**Comment by nsubiron** [comment]
Oh sorry, I gave you the wrong folder, it should be
`<sublime-text-data-path>/Packages/Theme - Solarized Space/`**`resources`**. 
In any case you probably have to create the last two folders.

I'm not sure about the directory layout in OSX, but I suppose you have the package file in 
`<sublime-text-data-path>/Installed Packages/Theme - Solarized Space.sublime-package`
(that's just a zip file containing the theme). To override files from it, you should add the folder
`<sublime-text-data-path>/Packages/Theme - Solarized Space`
and then add there the files you want to override with same name and folder as in the zip file. That's just the way Sublime Text 3 loads the [packages](https://www.sublimetext.com/docs/3/packages.html).

**Comment by dxps** [comment]
Hi nsubiron,

Thanks for the tip. That would to the job nice and easy.

You are right, on OSX the full path to the installed theme package is
 `/Users/<user>/Library/Application Support/Sublime Text 3/Installed Packages/Theme - Solarized Space.sublime-package`

Any update on the extra space in tabs? :-)

Thanks again!
