### ISSUE TITLE
Color scheme for Predawn

### ISSUE THREAD

**Issue by techrah** [nsubiron/sublime-theme-solarized-space#11]
![](/nsubiron/sublime-theme-solarized-space/raw/master/images/predawn.png)

I love the Predawn theme but can't figure out what color scheme is being used with it (code side). The only color schemes included in the package are `Solarized V (Light)` and `Solarized V Markdown (Light)`.

Can anyone explain?

**Comment by nsubiron** [comment]
Hi @ryanhomer,

It's [gruvbox](https://packagecontrol.io/packages/gruvbox), not included with this package though.

**Comment by techrah** [comment]
Oh, I love gruvbox. Thanks!
