### ISSUE TITLE
Theme overrides "Open all with current extension as..." and highlights incorrectly

### ISSUE THREAD

**Issue by henrahmagix** [nsubiron/sublime-theme-solarized-space#2]
Whenever I open a Sass file with the `Solarized Space Light.sublime-theme`, it selects the `Theme – Solarized Space/Sass` syntax, which is broken:
![image](https://cloud.githubusercontent.com/assets/1429026/15070226/d9de3218-137a-11e6-8256-4f85e649719f.png)

So I select `Open all with current extension as...` and select `Sass` at the root list, which I think comes from https://github.com/nathos/sass-textmate-bundle, and I get the highlighting I'm used to:
![image](https://cloud.githubusercontent.com/assets/1429026/15070244/ef52fca0-137a-11e6-946a-b626d79e753d.png)

But that configuration is ignored by this theme, and it will always choose the incorrect `Theme – Solarized Space/Sass` every time I open a Sass file.

**Comment by henrahmagix** [comment]
Switching themes did not fix this. I had to uninstall this package for correct functionality to return.

**Comment by nsubiron** [comment]
I added to the theme few language definitions to be able to have custom icons for those, among them sass, which just includes default css I think.
I didn't take into account that they could block language files in other packages. I guess is best removing the language definitions from the theme altogether.

**Comment by henrahmagix** [comment]
Thanks!
