### ISSUE TITLE
Extra padding is still present on OSX

### ISSUE THREAD

**Issue by dxps** [nsubiron/sublime-theme-solarized-space#7]
Hi nsubiron,

I keep using your theme as I think is lovely! :-)
I just received the update (v0.4.3), but I'm sorry to say that the extra padding on tab is still present.
![image](https://cloud.githubusercontent.com/assets/14140226/16999164/4c260a96-4ec5-11e6-8d39-26d7621403aa.png)

Thanks.

**Comment by nsubiron** [comment]
Hi visvadw,

Thanks for the report, but I'm not able to reproduce it. I tried on a Virtualbox and seems to be fine
![tab](https://cloud.githubusercontent.com/assets/4332953/17047264/6608ff62-501f-11e6-9210-80b79c2616b6.png)

**Comment by dxps** [comment]
Hi nsubiron,

I understand, but if you could tell me about some parameters that I may play with on my installation (`/Users/<user>/Library/Application Support/Sublime Text 3/Packages/Theme - Solarized Space/Solarized Space Light.sublime-theme`), I will try to find the root cause.

I really want to fix it as it is my favourite theme. In the near future, I will try to find some time to read how theming works on ST3.

Thanks anyway for the effort! 👍

**Comment by nsubiron** [comment]
Yes, no worries.

The sublime-theme file is just a json. The tab control options are actually at the beginning of the file, try tweaking things there, specifically "content_margin" at line 45 is the one I changed in the last commit.

**Comment by dxps** [comment]
As I could not rapidly find the root cause of this issue, I just started with version `0.3.2` of the theme and tweaked a little some tab related sizes. And the result looks pretty much the way I wanted to be.

![image](https://cloud.githubusercontent.com/assets/14140226/17117471/cfd11ce8-52c4-11e6-9893-6949b37f1537.png)

You may close the issue if don't have the time, patience or motivation to see what's the problem, starting with version `0.4.0`. :-)

Once again, thanks for the feedback and help!
