### ISSUE TITLE
Change selection highlights

### ISSUE THREAD

**Issue by xelra** [nsubiron/sublime-theme-solarized-space#8]
Is it possible to change how the selection is highlighted? You theme looks very nice and everything is flat, but when making a text selection, the highlight has the those borders and rounded corners. Is it possible to make the selection simply flat?

**Comment by nsubiron** [comment]
I'm afraid not. It seems there is no way in Sublime Text to do that: https://forum.sublimetext.com/t/remove-rounded-corners-from-text-selection-highlights/4787/5
